# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

lane :test do
  run_tests(
    scheme: "SbankenClient",
    devices: [
      "iPhone 6s",
      "iPhone X",
      "iPad Air"
    ],
    output_types: "junit"
  )

  xcov(
    project: "SbankenClient.xcodeproj",
    scheme: "SbankenClient",
    output_directory: "fastlane/xcov_output"
  )
end
